# Pandas Practice Workbook — Netflix Dataset (125 Questions)
**Prepared by Ananda Rimal** · Dataset: `netflix_titles.csv`

**Columns:** `show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description`

**Instructions**
- Write your answer in the code cell **below each question**
- Every answer must be pandas code — no manual counting
- Sections G (GroupBy) and H (Cleaning) may need columns you create along the way — read carefully

| Section | Topic | Questions |
|---------|-------|-----------|
| A | First Analysis of Data | 15 |
| B | Selection with `[]`, `.loc`, `.iloc` | 25 |
| C | Conditions (with `.loc`) | 20 |
| D | Sorting | 10 |
| E | Updating Data | 15 |
| F | GroupBy | 20 |
| G | Cleaning | 20 |
| **Total** | | **125** |

## Section A — First Analysis of Data (Q1–Q15)

#### Q1. Load the dataset into a DataFrame called `df` and display the first 5 rows.

In [ ]:
import pandas as pd
df = pd. read_csv ("/content/netflix_dataset.csv")

#### Q2. Display the **last 7 rows** of the DataFrame.

In [ ]:
df.tail(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8800,s8801,Movie,Lost Season Revealed,Pablo Sharma,"Chen Cohen, Liam Zhao, Ethan Gurung",India,"November 19, 2018",2017,TV-MA,123 min,"Classic Movies, Children & Family Movies","On the eve of a wedding, a young journalist le..."
8801,s8802,Movie,Our Storm Files,Noah Weber,"Ji-hoon Petrov, Ahmed Johnson, Rajesh Kim",Germany,"March 17, 2019",2018,TV-14,215 min,Romantic Movies,"After a chance encounter, a widowed farmer ris..."
8802,s8803,Movie,Sacred Season Experiment,NaN,"Sven Bakshi, Meera Petrov, Ananya Brown, Ji-ho...",NaN,"May 12, 2019",2018,TV-14,54 min,"Sports Movies, Faith & Spirituality, Romantic ...","Torn between duty and desire, a widowed farmer..."
8803,s8804,Movie,Burning Mirror Project,Omar Petrov,"Bikash Schmidt, Kenji Wang","Germany, United States","November 5, 2020",2015,TV-14,41 min,Anime Features,"Torn between duty and desire, a widowed farmer..."
8804,s8805,TV Show,Amazing House Rising,NaN,"Chen Zhao, Sunita Rahman, Sunita Schmidt, Zara...",India,"May 1, 2020",2020,TV-MA,1 Season,"TV Thrillers, International TV Shows","Torn between duty and desire, an ambitious che..."
8805,s8806,Movie,Sweet Heart,Sarah Miller,"Rahul Smith, Noah Singh, Sophie Santos, Priya ...",India,"March 25, 2020",2019,NR,46 min,"Independent Movies, LGBTQ Movies, Horror Movies","Decades after the war, a struggling musician u..."
8806,s8807,TV Show,A Girl,NaN,"Ahmed Murphy, Min-ji Bakshi, Sophie Patel, Nis...",Norway,"March 20, 2021",2021,TV-MA,2 Seasons,"TV Action & Adventure, TV Shows, Anime Series","After a chance encounter, an aging film star u..."

#### Q3. How many rows and columns does the dataset have?

In [ ]:
df.shape

(8807, 12)

#### Q4. Display the names of all columns.

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

#### Q5. Use `info()` — which columns have missing values, and what is the data type of each column?

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6166 non-null   object
 4   cast          7954 non-null   object
 5   country       8038 non-null   object
 6   date_added    8799 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8799 non-null   object
 9   duration      8803 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

#### Q6. Use `describe()` on the numeric columns. What is the minimum and maximum `release_year`?

In [ ]:
df.describe() #1925 is the minimum release year while 2021 is the maximum

       release_year
count    8807.00000
mean     2012.54116
std        11.09967
min      1925.00000
25%      2011.00000
50%      2016.00000
75%      2019.00000
max      2021.00000

#### Q7. Use `describe(include="object")` on the text columns. Which value appears most often in the `type` column?

In [ ]:
df.describe(include="object")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8807,8807,8807,6166,7954,8038,8799,8799,8803,8807,8807
unique,8807,2,7373,2414,7953,755,3618,17,231,3398,1152
top,s8807,Movie,Modern Empire Project,Nisha Verma,"Ravi Park, Ahmed Rossi",United States,"February 11, 2021",TV-MA,1 Season,LGBTQ Movies,"Torn between duty and desire, a teenage prodig..."
freq,1,6035,7,10,2,2314,13,2924,1586,114,17

#### Q8. Count the missing values in **every** column with one command.

In [ ]:
df.isna().sum()

show_id            0
type               0
title              0
director        2641
cast             853
country          769
date_added         8
release_year       0
rating             8
duration           4
listed_in          0
description        0
dtype: int64

#### Q9. Which single column has the **most** missing values?

In [ ]:
df.isna().sum().idxmax()

'director'

#### Q10. How many **unique** values are in the `rating` column? Display them.

In [ ]:
df["rating"].nunique()

17

In [ ]:
df["rating"].unique()

array(['R', 'TV-MA', 'TV-14', 'TV-Y', 'TV-Y7', 'TV-PG', 'TV-G', 'PG-13',
       'PG', 'NR', 'G', 'NC-17', 'TV-Y7-FV', 'UR', nan, '61 min',
       '62 min', '74 min'], dtype=object)

#### Q11. Show 5 **random** rows using `sample()`.

In [ ]:

df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2973,s2974,Movie,Amazing Machine in Paris,Aiko Bakshi,"Sven Fernandez, Omar Smith, Sunita Gurung, Kwa...",United States,"July 9, 2020",2013,TV-MA,92 min,"Stand-Up Comedy, Anime Features, Horror Movies","Determined to start over, a retired detective ..."
1560,s1561,Movie,The Mirror of Mumbai,Zara Novak,"Maria Thapa, Layla Mishra, Sophie Chen, Kwame ...",NaN,"November 19, 2021",2021,TV-PG,171 min,Comedies,"Decades after the war, a small-town teacher fi..."
7561,s7562,TV Show,Lost Escape Diaries,NaN,"Aarav Rahman, Chloe Sharma, Pierre Wang, Ji-ho...",United States,"December 13, 2016",2016,TV-MA,1 Season,Spanish-Language TV Shows,"In a small town, a widowed farmer learns that ..."
3349,s3350,Movie,The Family Project,Lucia Sharma,"Bikash Thapa, Rahul Hassan, Tomasz Nguyen, Min...",Philippines,"November 10, 2018",2009,R,51 min,"Cult Movies, International Movies, Classic Movies","In the middle of a heatwave, a small-town teac..."
3451,s3452,Movie,Endless Song Uncovered,Tomasz Silva,"Omar Okafor, Chloe Rahman, Emma Rossi, Emma Ta...",Mexico,"June 22, 2021",2021,PG,194 min,"LGBTQ Movies, Thrillers, Children & Family Movies","Torn between duty and desire, an ambitious che..."

#### Q12. What is the memory usage of the DataFrame? (hint: `info()` or `memory_usage()`)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6166 non-null   object
 4   cast          7954 non-null   object
 5   country       8038 non-null   object
 6   date_added    8799 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8799 non-null   object
 9   duration      8803 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

#### Q13. Display the data type of only the `release_year` column.

In [ ]:
df["release_year"].dtype

dtype('int64')

#### Q14. Count how many titles are of each `type` using `value_counts()`.

In [ ]:
df["type"].value_counts()

type
Movie      6035
TV Show    2772
Name: count, dtype: int64

#### Q15. Check: does the dataset contain any **fully duplicated** rows?

In [ ]:
df.duplicated().any()

np.False_

## Section B — Selection with `[]`, `.loc`, `.iloc` (Q16–Q40)
*(Q16–Q30: default 0,1,2,... index · Q31–Q40: after `set_index("show_id")`)*

#### Q16. Select the `title` column as a **Series**.

In [ ]:
df ['title']

0           Secret Storm Forever
1                   Black Forest
2               An Legacy Rising
3             My Journey Diaries
4                    Autumn Love
                  ...
8802    Sacred Season Experiment
8803      Burning Mirror Project
8804        Amazing House Rising
8805                 Sweet Heart
8806                      A Girl
Name: title, Length: 8807, dtype: object

In [ ]:
type(df['title'])

pandas.core.series.Series

#### Q17. Select the `title` column as a **DataFrame** (hint: double brackets).

In [ ]:
df [['title']]

                         title
0         Secret Storm Forever
1                 Black Forest
2             An Legacy Rising
3           My Journey Diaries
4                  Autumn Love
...                        ...
8802  Sacred Season Experiment
8803    Burning Mirror Project
8804      Amazing House Rising
8805               Sweet Heart
8806                    A Girl

[8807 rows x 1 columns]

In [ ]:
type(df[["title"]])

pandas.core.frame.DataFrame

#### Q18. Select the columns `title`, `type`, and `country` together.

In [ ]:
df[['title','type','country']]

                         title     type                 country
0         Secret Storm Forever    Movie                     NaN
1                 Black Forest    Movie                    Peru
2             An Legacy Rising  TV Show                   India
3           My Journey Diaries    Movie       Indonesia, France
4                  Autumn Love    Movie          United Kingdom
...                        ...      ...                     ...
8802  Sacred Season Experiment    Movie                     NaN
8803    Burning Mirror Project    Movie  Germany, United States
8804      Amazing House Rising  TV Show                   India
8805               Sweet Heart    Movie                   India
8806                    A Girl  TV Show                  Norway

[8807 rows x 3 columns]

#### Q19. Select the first 10 rows using `.iloc`.

In [ ]:
df.iloc[0:10]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Secret Storm Forever,Marcus Garcia,"Daniel Andersen, Olivia Mishra, Chen Hassan, S...",NaN,"March 27, 2019",2013,R,182 min,"Sci-Fi & Fantasy, Horror Movies","After a chance encounter, a group of college f..."
1,s2,Movie,Black Forest,Ethan Silva,"Min-ji Bakshi, Hassan Sharma, Rajesh Baral",Peru,"March 19, 2011",2011,TV-MA,114 min,"Children & Family Movies, Documentaries, Indep...","Determined to start over, a widowed farmer rac..."
2,s3,TV Show,An Legacy Rising,James Rossi,"Maria Verma, Lucia Tanaka, Omar Novak",India,"May 19, 2015",2013,TV-MA,1 Season,"TV Mysteries, International TV Shows, Anime Se...","In the middle of a heatwave, an ambitious chef..."
3,s4,Movie,My Journey Diaries,Bikash Okafor,"Chen Reyes, Sunita Adhikari, Maria Novak","Indonesia, France","September 12, 2021",2021,TV-14,122 min,Romantic Movies,"Decades after the war, a retired detective mus..."
4,s5,Movie,Autumn Love,Priya Fernandez,"Aiko Yamamoto, Nisha Bakshi, Sven Wang, Tomasz...",United Kingdom,"May 2, 2020",2015,R,93 min,Movies,"Torn between duty and desire, a ruthless busin..."
5,s6,TV Show,The Island Chronicles,NaN,"Ananya Miller, Omar Johnson",United Kingdom,"March 7, 2020",2019,TV-Y,1 Season,TV Horror,"Torn between duty and desire, an ambitious che..."
6,s7,Movie,Red Detective Forever,Ravi Verma,"Ravi Hassan, Daniel Reyes, Olivia Mendez, Marc...",United States,"January 14, 2017",2017,TV-14,243 min,"Classic Movies, Thrillers","Determined to start over, a group of college f..."
7,s8,Movie,Modern Night,Nisha Sharma,"Sunita Park, Sophie Brown, Layla Yamamoto",India,"February 18, 2021",2012,TV-14,59 min,"Sci-Fi & Fantasy, Anime Features, Action & Adv...","Facing financial ruin, two estranged siblings ..."
8,s9,TV Show,Dark Promise in Paris,NaN,"Ingrid Tanaka, Priya Zhao, Aiko Novak, Kwame S...",Mexico,"September 26, 2018",2015,TV-Y7,1 Season,"TV Mysteries, Kids' TV","Haunted by the past, an aging film star sets o..."
9,s10,TV Show,Rising Forest Part Two,Ethan Cohen,"Priya Dubois, Sophie Nguyen, Noah Kowalski, Sa...",United States,"November 8, 2016",2015,TV-MA,1 Season,"TV Horror, Teen TV Shows, Science & Nature TV","On the eve of a wedding, a rookie police offic..."

#### Q20. Select rows with labels 10 to 20 using `.loc`. How many rows do you get and why?

In [ ]:
df.loc [10:20]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,s11,TV Show,Hidden Journey,Noah Fernandez,"Ahmed Adhikari, Min-ji Hassan, Tomasz Mendez",Canada,"December 21, 2015",2009,TV-14,4 Seasons,"International TV Shows, TV Action & Adventure,...","During a nationwide blackout, a teenage prodig..."
11,s12,TV Show,Amazing King of Mumbai,Rahul Mendez,"Sven Novak, Maria Cohen, Kenji Reyes",United States,"January 23, 2019",2019,TV-PG,8 Seasons,TV Thrillers,"On the eve of a wedding, a young journalist le..."
12,s13,TV Show,Black Legacy,NaN,"Isabella Schmidt, Liam Brown",United States,"April 5, 2012",1989,TV-MA,1 Season,Korean TV Shows,"Following a mysterious disappearance, a ruthle..."
13,s14,TV Show,My Hunter Part Two,NaN,"Tomasz Silva, Nisha Petrov, Rahul Fernandez, M...",United States,"February 6, 2019",2018,TV-MA,1 Season,British TV Shows,"Haunted by the past, a teenage prodigy builds ..."
14,s15,Movie,Sacred Game Experiment,Rajesh Sharma,"Pierre Costa, Chen Reyes, Priya Miller, Nisha ...",Switzerland,"February 5, 2021",2008,TV-MA,43 min,LGBTQ Movies,"Torn between duty and desire, a widowed farmer..."
15,s16,Movie,A Song in Paris,Kenji Schmidt,"Rajesh Iyer, Wei Adhikari, Tomasz Rossi, Min-j...",United States,"July 17, 2013",2009,TV-PG,138 min,"Faith & Spirituality, Romantic Movies","In a small town, a retired detective races aga..."
16,s17,TV Show,Last Machine Reborn,NaN,"Rajesh Dubois, Sven Cohen, Valentina Kowalski,...",Spain,"January 14, 2021",2020,TV-MA,6 Seasons,TV Mysteries,"In the middle of a heatwave, a young journalis..."
17,s18,Movie,A Story Chronicles,Valentina Santos,"Bikash Silva, Aarav Schmidt, James Ibrahim, Ra...",Australia,"September 17, 2019",2018,TV-G,63 min,Romantic Movies,"On the eve of a wedding, a struggling musician..."
18,s19,Movie,Hidden Escape,Bikash Nguyen,"Liam Smith, Marcus Chen, Ahmed Singh, Hassan L...","Germany, United States","August 27, 2016",2008,PG-13,74 min,"Action & Adventure, Cult Movies, Stand-Up Comedy","During a nationwide blackout, a struggling mus..."
19,s20,Movie,White Secret Experiment,Camille Murphy,NaN,NaN,"November 11, 2019",2017,TV-14,47 min,"Stand-Up Comedy, Action & Adventure, Comedies","On the eve of a wedding, a young journalist se..."
20,s21,Movie,Silent Secret Affair,Elena Sharma,"Camille Dubois, Isabella Okafor, Arjun Bakshi,...",United States,"October 14, 2014",1999,TV-MA,80 min,Children & Family Movies,"Torn between duty and desire, an aging film st..."

#### Q21. Using `.iloc`, select rows at positions 5 to 14 (10 rows). Compare with Q20 — why is the row count logic different?

In [ ]:
df.iloc [5:14]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5,s6,TV Show,The Island Chronicles,NaN,"Ananya Miller, Omar Johnson",United Kingdom,"March 7, 2020",2019,TV-Y,1 Season,TV Horror,"Torn between duty and desire, an ambitious che..."
6,s7,Movie,Red Detective Forever,Ravi Verma,"Ravi Hassan, Daniel Reyes, Olivia Mendez, Marc...",United States,"January 14, 2017",2017,TV-14,243 min,"Classic Movies, Thrillers","Determined to start over, a group of college f..."
7,s8,Movie,Modern Night,Nisha Sharma,"Sunita Park, Sophie Brown, Layla Yamamoto",India,"February 18, 2021",2012,TV-14,59 min,"Sci-Fi & Fantasy, Anime Features, Action & Adv...","Facing financial ruin, two estranged siblings ..."
8,s9,TV Show,Dark Promise in Paris,NaN,"Ingrid Tanaka, Priya Zhao, Aiko Novak, Kwame S...",Mexico,"September 26, 2018",2015,TV-Y7,1 Season,"TV Mysteries, Kids' TV","Haunted by the past, an aging film star sets o..."
9,s10,TV Show,Rising Forest Part Two,Ethan Cohen,"Priya Dubois, Sophie Nguyen, Noah Kowalski, Sa...",United States,"November 8, 2016",2015,TV-MA,1 Season,"TV Horror, Teen TV Shows, Science & Nature TV","On the eve of a wedding, a rookie police offic..."
10,s11,TV Show,Hidden Journey,Noah Fernandez,"Ahmed Adhikari, Min-ji Hassan, Tomasz Mendez",Canada,"December 21, 2015",2009,TV-14,4 Seasons,"International TV Shows, TV Action & Adventure,...","During a nationwide blackout, a teenage prodig..."
11,s12,TV Show,Amazing King of Mumbai,Rahul Mendez,"Sven Novak, Maria Cohen, Kenji Reyes",United States,"January 23, 2019",2019,TV-PG,8 Seasons,TV Thrillers,"On the eve of a wedding, a young journalist le..."
12,s13,TV Show,Black Legacy,NaN,"Isabella Schmidt, Liam Brown",United States,"April 5, 2012",1989,TV-MA,1 Season,Korean TV Shows,"Following a mysterious disappearance, a ruthle..."
13,s14,TV Show,My Hunter Part Two,NaN,"Tomasz Silva, Nisha Petrov, Rahul Fernandez, M...",United States,"February 6, 2019",2018,TV-MA,1 Season,British TV Shows,"Haunted by the past, a teenage prodigy builds ..."

#### Q22. Using `.loc`, select rows 0 to 9 with only the columns `title` and `release_year`.

In [ ]:
df.loc [0:9, ["title",'release_year']]

                    title  release_year
0    Secret Storm Forever          2013
1            Black Forest          2011
2        An Legacy Rising          2013
3      My Journey Diaries          2021
4             Autumn Love          2015
5   The Island Chronicles          2019
6   Red Detective Forever          2017
7            Modern Night          2012
8   Dark Promise in Paris          2015
9  Rising Forest Part Two          2015

#### Q23. Using `.iloc`, select the first 8 rows and the first 5 columns.

In [ ]:
df.iloc [0:8 , 0:5]

,show_id,type,title,director,cast
0,s1,Movie,Secret Storm Forever,Marcus Garcia,"Daniel Andersen, Olivia Mishra, Chen Hassan, S..."
1,s2,Movie,Black Forest,Ethan Silva,"Min-ji Bakshi, Hassan Sharma, Rajesh Baral"
2,s3,TV Show,An Legacy Rising,James Rossi,"Maria Verma, Lucia Tanaka, Omar Novak"
3,s4,Movie,My Journey Diaries,Bikash Okafor,"Chen Reyes, Sunita Adhikari, Maria Novak"
4,s5,Movie,Autumn Love,Priya Fernandez,"Aiko Yamamoto, Nisha Bakshi, Sven Wang, Tomasz..."
5,s6,TV Show,The Island Chronicles,NaN,"Ananya Miller, Omar Johnson"
6,s7,Movie,Red Detective Forever,Ravi Verma,"Ravi Hassan, Daniel Reyes, Olivia Mendez, Marc..."
7,s8,Movie,Modern Night,Nisha Sharma,"Sunita Park, Sophie Brown, Layla Yamamoto"

#### Q24. Using `.iloc`, select the **last row** of the DataFrame.

In [ ]:
df.iloc[[-1]]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8806,s8807,TV Show,A Girl,NaN,"Ahmed Murphy, Min-ji Bakshi, Sophie Patel, Nis...",Norway,"March 20, 2021",2021,TV-MA,2 Seasons,"TV Action & Adventure, TV Shows, Anime Series","After a chance encounter, an aging film star u..."

#### Q25. Using `.iloc`, select the last 5 rows and the last 2 columns (negative positions).

In [ ]:
df.iloc[-5:, -2:]

,listed_in,description
8802,"Sports Movies, Faith & Spirituality, Romantic ...","Torn between duty and desire, a widowed farmer..."
8803,Anime Features,"Torn between duty and desire, a widowed farmer..."
8804,"TV Thrillers, International TV Shows","Torn between duty and desire, an ambitious che..."
8805,"Independent Movies, LGBTQ Movies, Horror Movies","Decades after the war, a struggling musician u..."
8806,"TV Action & Adventure, TV Shows, Anime Series","After a chance encounter, an aging film star u..."

#### Q26. Using `.loc`, get the value of `title` for the row with label 50.

In [ ]:
df.loc [50 , "title"]

'Black Legacy Diaries'

#### Q27. Using `.iloc`, get the value in row position 100, column position 2. Which column is that?

In [ ]:
df.iloc [99, 1]

'Movie'

#### Q28. Using `.iloc`, select every 100th row (hint: slicing with a step `::100`).

In [ ]:
# Your answer here

#### Q29. Using `.loc`, select rows 0 to 4 and **all** columns from `title` to `country` (label slicing on columns!).

In [ ]:
# Your answer here

#### Q30. Select three specific rows by label — 3, 33, and 333 — in one `.loc` call.

In [ ]:
# Your answer here

#### Q31. Set `show_id` as the index of `df` (keep it for the rest of Section B). Display the head.

In [ ]:
# Your answer here

#### Q32. Using `.loc`, select the row with label `"s1"`.

In [ ]:
# Your answer here

#### Q33. Using `.loc`, select rows `"s10"` to `"s15"`. Does label slicing still include the end?

In [ ]:
# Your answer here

#### Q34. Using `.iloc`, select the row at position 0. Is it the same row as label `"s1"`?

In [ ]:
# Your answer here

#### Q35. Using `.loc`, get the `title` and `type` of the show with id `"s500"`.

In [ ]:
# Your answer here

#### Q36. Using `.iloc`, select the row at position 499. Is its label `"s500"`? Explain why or why not in a comment.

In [ ]:
# Your answer here

#### Q37. Using `.loc`, select shows `"s1"`, `"s100"`, and `"s1000"` with columns `title` and `release_year`.

In [ ]:
# Your answer here

#### Q38. What happens if you run `df.loc[0]` now? Try it, read the error, and explain in a comment.

In [ ]:
# Your answer here

#### Q39. Using `.iloc`, select rows at positions [0, 99, 999] in one call.

In [ ]:
# Your answer here

#### Q40. Reset the index back to 0,1,2,... using `reset_index()`. Display the head.

In [ ]:
# Your answer here

## Section C — Conditions with `.loc` (Q41–Q60)
*Write every filter with `df.loc[condition]` or `df.loc[condition, columns]` style where possible.*

#### Q41. Select all rows where `type` is `"Movie"`.

In [ ]:
# Your answer here

#### Q42. Select all rows where `type` is `"TV Show"` — show only `title` and `country` using one `.loc` call.

In [ ]:
# Your answer here

#### Q43. Select all titles released in 2021.

In [ ]:
# Your answer here

#### Q44. Select all titles released **before** 2000.

In [ ]:
# Your answer here

#### Q45. Select all titles released between 2015 and 2020 (inclusive) — two conditions with `&`.

In [ ]:
# Your answer here

#### Q46. Select all Movies released after 2019 (two conditions).

In [ ]:
# Your answer here

#### Q47. Select all titles where `rating` is `"TV-MA"`.

In [ ]:
# Your answer here

#### Q48. Select all titles where `rating` is either `"PG"` or `"PG-13"` using `.isin()`.

In [ ]:
# Your answer here

#### Q49. Select all titles where `rating` is **NOT** `"TV-MA"` (hint: `~` or `!=`).

In [ ]:
# Your answer here

#### Q50. Select all titles where `country` is exactly `"India"`.

In [ ]:
# Your answer here

#### Q51. Select all titles where `country` **contains** `"India"` (hint: `str.contains`, use `na=False`). Why is the row count different from the previous question?

In [ ]:
# Your answer here

#### Q52. Select all Movies from the United States — show only `title` and `release_year`.

In [ ]:
# Your answer here

#### Q53. Select all titles where `director` is missing (hint: `isna()`).

In [ ]:
# Your answer here

#### Q54. Select all titles where `director` is **not** missing.

In [ ]:
# Your answer here

#### Q55. Select all TV Shows released in 2020 **or** 2021.

In [ ]:
# Your answer here

#### Q56. Select all titles whose `title` starts with the letter `"A"` (hint: `str.startswith`, `na=False`).

In [ ]:
# Your answer here

#### Q57. Select all titles whose `title` contains the word `"Love"`.

In [ ]:
# Your answer here

#### Q58. Using `.loc` with a condition, show the `title`, `rating`, and `release_year` of all Movies rated `"R"`.

In [ ]:
# Your answer here

#### Q59. Count how many Movies were released after 2015 (condition + `len()` or `.shape`).

In [ ]:
# Your answer here

#### Q60. Challenge: select all Movies that are from India **or** Nepal and released after 2010 — careful with brackets around the `|` condition!

In [ ]:
# Your answer here

## Section D — Sorting (Q61–Q70)

#### Q61. Sort the DataFrame by `release_year` ascending. Show the head — what are the oldest titles?

In [ ]:
# Your answer here

#### Q62. Sort by `release_year` **descending**. Show the 10 newest titles.

In [ ]:
# Your answer here

#### Q63. Sort by `title` alphabetically.

In [ ]:
# Your answer here

#### Q64. Sort by `release_year` descending AND `title` ascending at the same time (list of columns + list of ascending values).

In [ ]:
# Your answer here

#### Q65. Sort by `rating`, and show only `title` and `rating` in the result.

In [ ]:
# Your answer here

#### Q66. Sort the **index** using `sort_index()` (useful after filtering).

In [ ]:
# Your answer here

#### Q67. Show the 5 oldest Movies (filter first, then sort, then head).

In [ ]:
# Your answer here

#### Q68. Show the 5 newest TV Shows.

In [ ]:
# Your answer here

#### Q69. Sort by `country` and put the missing values **first** (hint: `na_position="first"`).

In [ ]:
# Your answer here

#### Q70. What does `ascending=[False, True]` mean when sorting by two columns? Demonstrate with `release_year` and `title` and explain in a comment.

In [ ]:
# Your answer here

## Section E — Updating Data (Q71–Q85)

#### Q71. Rename the column `listed_in` to `genres` (keep this change).

In [ ]:
# Your answer here

#### Q72. Create a new column `age_years` = 2026 minus `release_year`.

In [ ]:
# Your answer here

#### Q73. Create a column `is_movie` that is `True` when `type` is `"Movie"`.

In [ ]:
# Your answer here

#### Q74. Create a column `is_recent` that is `True` when `release_year >= 2020`.

In [ ]:
# Your answer here

#### Q75. Using `.loc` with a condition, set `rating` to `"UNRATED"` for all rows where `rating` is missing.

In [ ]:
# Your answer here

#### Q76. Replace the value `"United States"` with `"USA"` in the `country` column (hint: `replace`).

In [ ]:
# Your answer here

#### Q77. Convert all titles to UPPERCASE into a new column `title_upper` (hint: `str.upper`).

In [ ]:
# Your answer here

#### Q78. Create a column `title_length` = number of characters in each title (hint: `str.len`).

In [ ]:
# Your answer here

#### Q79. Using `.loc`, change the `title` of the row with index label 0 to `"My Favourite Show"`. Display that row to confirm.

In [ ]:
# Your answer here

#### Q80. Add a column `platform` where every row has the value `"Netflix"`.

In [ ]:
# Your answer here

#### Q81. Delete the column `title_upper` using `drop`.

In [ ]:
# Your answer here

#### Q82. Change `release_year` to type `int32` using `astype`. Check with `dtypes`.

In [ ]:
# Your answer here

#### Q83. Using `.loc` with a condition, create/overwrite a column `era` = `"old"` for titles before 2010 and `"new"` for 2010 onward (two `.loc` assignments, or `np.where`).

In [ ]:
# Your answer here

#### Q84. Increase `age_years` by 1 for **all** rows in one operation.

In [ ]:
# Your answer here

#### Q85. Explain in a markdown comment: why is `df.loc[condition, "col"] = value` the SAFE way to update, instead of `df[condition]["col"] = value`? (SettingWithCopyWarning!)

In [ ]:
# Your answer here

## Section F — GroupBy (Q86–Q105)

#### Q86. Group by `type` and count the number of titles in each group (`size()`).

In [ ]:
# Your answer here

#### Q87. Group by `rating` and count titles. Which rating is most common?

In [ ]:
# Your answer here

#### Q88. Group by `release_year` and count titles. Which year had the most releases?

In [ ]:
# Your answer here

#### Q89. Group by `type` and find the **minimum** and **maximum** `release_year` for each (hint: `agg(["min","max"])`).

In [ ]:
# Your answer here

#### Q90. Group by `type` and compute the **average** `age_years`.

In [ ]:
# Your answer here

#### Q91. Group by `country` and count titles — show only the top 10 (sort + head).

In [ ]:
# Your answer here

#### Q92. Group by `rating` and compute the average `title_length`.

In [ ]:
# Your answer here

#### Q93. Group by `era` (from Q83) and count Movies vs TV Shows (hint: group by TWO columns).

In [ ]:
# Your answer here

#### Q94. Group by `type` and `rating` together and count. Display the result with `unstack()`.

In [ ]:
# Your answer here

#### Q95. For Movies only: group by `release_year` and count — how many movies came out each year since 2015? (filter first, then group, then `.tail()`)

In [ ]:
# Your answer here

#### Q96. Group by `country` and compute the average `release_year` — which 5 countries have the 'newest' catalogs on average? (sort descending, head)

In [ ]:
# Your answer here

#### Q97. Use `value_counts()` on `genres` — why does this NOT give clean genre counts? Explain in a comment (hint: multiple genres in one cell).

In [ ]:
# Your answer here

#### Q98. Group by `is_recent` and count — how many recent vs old titles?

In [ ]:
# Your answer here

#### Q99. Group by `type` and use `.agg()` with a dictionary: count of `title` and mean of `age_years` in ONE command.

In [ ]:
# Your answer here

#### Q100. Group by `rating` and show the **number of unique countries** per rating (hint: `nunique`).

In [ ]:
# Your answer here

#### Q101. Using `groupby` + `head(1)`, show the FIRST title (by current order) in each `type` group.

In [ ]:
# Your answer here

#### Q102. Group by `release_year` and count, then plot it with `.plot()` (line chart). What trend do you see?

In [ ]:
# Your answer here

#### Q103. Group by `year_added`-style logic isn't possible yet — `date_added` is still text! Group by the **first 4 characters trick is wrong**. Explain in a comment why we need Section G (Cleaning) before we can group by the year a title was ADDED.

In [ ]:
# Your answer here

#### Q104. Group by `type` and compute the **median** `release_year`.

In [ ]:
# Your answer here

#### Q105. Challenge: for each `rating`, what percentage of titles are Movies? (hint: group by rating, compute the mean of `is_movie`, multiply by 100)

In [ ]:
# Your answer here

## Section G — Cleaning (Q106–Q125)

#### Q106. Re-check missing values per column (things changed since Section A!).

In [ ]:
# Your answer here

#### Q107. Fill missing `director` values with `"Unknown"`.

In [ ]:
# Your answer here

#### Q108. Fill missing `cast` values with `"Unknown"`.

In [ ]:
# Your answer here

#### Q109. Fill missing `country` values with the **most common** country (hint: `mode()[0]`).

In [ ]:
# Your answer here

#### Q110. Count the rows where `date_added` is missing, then drop those rows.

In [ ]:
# Your answer here

#### Q111. `date_added` has extra spaces in some rows — strip them (hint: `str.strip`).

In [ ]:
# Your answer here

#### Q112. Convert `date_added` to datetime with `pd.to_datetime`. Check the dtype after.

In [ ]:
# Your answer here

#### Q113. NOW create `year_added` = `.dt.year` and `month_added` = `.dt.month_name()`.

In [ ]:
# Your answer here

#### Q114. Group by `year_added` and count — which year did Netflix add the most content? (This is the question F103 could not answer!)

In [ ]:
# Your answer here

#### Q115. Group by `month_added` and count — which month is most popular for adding content?

In [ ]:
# Your answer here

#### Q116. Look at the `duration` column with `unique()` (first 20 values) — what TWO different formats do you see?

In [ ]:
# Your answer here

#### Q117. Extract the number from `duration` into a new column `duration_int` (hint: `str.extract(r"(\\d+)")` then `astype(float)`).

In [ ]:
# Your answer here

#### Q118. For Movies only: what is the average, minimum, and maximum duration in minutes?

In [ ]:
# Your answer here

#### Q119. For TV Shows only: how many have more than 5 seasons? Show their titles.

In [ ]:
# Your answer here

#### Q120. Check duplicated **titles** (not full rows): are there any titles that appear more than once? Display them.

In [ ]:
# Your answer here

#### Q121. Are those duplicated titles real duplicates or different shows? Inspect a few with `.loc` and explain in a comment.

In [ ]:
# Your answer here

#### Q122. The `rating` column contains some WRONG values that are actually durations (like `"74 min"`) — find them (hint: `str.contains("min", na=False)`).

In [ ]:
# Your answer here

#### Q123. Fix those wrong rating rows: set their `rating` to `"UNRATED"` using `.loc`.

In [ ]:
# Your answer here

#### Q124. Final check: run `info()` and `isna().sum()` — is the dataset clean now? Summarize what you fixed in a comment.

In [ ]:
# Your answer here

#### Q125. Save your cleaned DataFrame to a new file `netflix_clean.csv` (without the index). This file is your submission proof!

In [ ]:
# Your answer here

---
## Submission
- Answer **all 125 questions** — partial answers get partial marks
- Run All must work top to bottom without errors (−5 marks if it crashes)
- Submit BOTH files: `YourName_workbook.ipynb` and `netflix_clean.csv`