# Joins in Pandas

In pandas, we combine two DataFrames using **`pd.merge()`** — just like SQL joins.

Types of joins:
1. **Inner Join** — only matching rows
2. **Left Join** — all rows from left + matches from right
3. **Right Join** — all rows from right + matches from left
4. **Outer Join** — all rows from both

In [ ]:
import pandas as pd

# Two simple DataFrames
students = pd.DataFrame({
    'student_id': [1, 2, 3, 4],
    'name': ['Anita', 'Bibek', 'Chandra', 'Dipesh']
})

marks = pd.DataFrame({
    'student_id': [1, 2, 3, 5],
    'marks': [85, 90, 78, 88]
})

In [ ]:
students

   student_id     name
0           1    Anita
1           2    Bibek
2           3  Chandra
3           4   Dipesh

In [ ]:
marks

   student_id  marks
0           1     85
1           2     90
2           3     78
3           5     88

## 1. Inner Join
Keeps only rows where `student_id` exists in **both** tables.

Here: ids 1, 2, 3 (id 4 has no marks, id 5 has no student — both dropped).

In [ ]:
inner = pd.merge(students, marks, on='student_id', how='inner')
inner

   student_id     name  marks
0           1    Anita     85
1           2    Bibek     90
2           3  Chandra     78

## 2. Left Join
Keeps **all rows from the left** table (`students`). Missing marks become `NaN`.

In [ ]:
left = pd.merge(students, marks, on='student_id', how='left')
left

   student_id     name  marks
0           1    Anita   85.0
1           2    Bibek   90.0
2           3  Chandra   78.0
3           4   Dipesh    NaN

## 3. Right Join
Keeps **all rows from the right** table (`marks`). Missing names become `NaN`.

In [ ]:
right = pd.merge(students, marks, on='student_id', how='right')
right

   student_id     name  marks
0           1    Anita     85
1           2    Bibek     90
2           3  Chandra     78
3           5      NaN     88

## 4. Outer Join
Keeps **all rows from both** tables. Missing values become `NaN`.

In [ ]:
outer = pd.merge(students, marks, on='student_id', how='outer')
outer

   student_id     name  marks
0           1    Anita   85.0
1           2    Bibek   90.0
2           3  Chandra   78.0
3           4   Dipesh    NaN
4           5      NaN   88.0

## Quick Summary

| Join type | `how=` | Keeps |
|-----------|--------|-------|
| Inner | `'inner'` | Only matching rows |
| Left | `'left'` | All left rows |
| Right | `'right'` | All right rows |
| Outer | `'outer'` | All rows from both |